//! `generate_image` — multimodal generation through `stella-media`'s
//! `MediaProvider` port, BYOK like everything else: the tool registers only
//! when an image-capable provider key is present in the environment
//! (`ZAI_API_KEY` or `OPENAI_API_KEY`), mirroring the issue tools'
//! conditional registration — no key, no dead schema.
//!
//! Artifact discipline (`stella-media`): generated bytes are persisted
//! through the `ArtifactStore` into `.stella/artifacts/` — the single
//! allowed writer — and the tool reports the citation-ready path. Video is
//! deliberately not exposed as a tool yet: it is an async, dollar-cost job
//! behind a consent gate, the wrong shape for an unattended tool call.

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;
use stella_media::{ArtifactStore, ImageRequest, ImageSize, MediaProvider};
use stella_protocol::tool::{ToolOutput, ToolSchema};

use crate::registry::Tool;

/// An image-capable media backend resolved from the environment.
pub struct MediaBackend {
    pub provider: Arc<dyn MediaProvider>,
}

impl MediaBackend {
    pub fn new(provider: Arc<dyn MediaProvider>) -> Self {
        Self { provider }
    }
}

/// Detect an image-capable BYOK backend from provider env keys. Z.ai wins
/// when several are set (the same "most specific configured backend first"
/// rule as the issue tools' Linear-over-GitHub precedence).
pub fn detect_media_backend() -> Option<MediaBackend> {
    if let Ok(key) = stella_media::ApiKey::from_env("ZAI_API_KEY") {
        return Some(MediaBackend::new(Arc::new(
            stella_media::adapters::ZaiImageProvider::new(
                key,
                stella_media::adapters::zai_image::DEFAULT_MODEL,
            ),
        )));
    }
    if let Ok(key) = stella_media::ApiKey::from_env("OPENAI_API_KEY") {
        return Some(MediaBackend::new(Arc::new(
            stella_media::adapters::OpenAiImageProvider::new(
                key,
                stella_media::adapters::openai_image::DEFAULT_MODEL,
            ),
        )));
    }
    None
}

pub struct GenerateImage(pub Arc<dyn MediaProvider>);

#[async_trait]
impl Tool for GenerateImage {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_image".into(),
            description: "Generate an image from a text prompt and save it under \
                          .stella/artifacts/. Returns the file path, model, and cost. \
                          Uses the configured BYOK image provider."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "What to generate"
                    },
                    "size": {
                        "type": "string",
                        "description": "WIDTHxHEIGHT, e.g. 1024x1024 (the default)"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["prompt"]
            }),
            read_only: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(prompt) = input.get("prompt").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`prompt` is required".into(),
            };
        };
        let size = match input.get("size").and_then(|v| v.as_str()) {
            Some(raw) => match raw.parse::<ImageSize>() {
                Ok(s) => s,
                Err(_) => {
                    return ToolOutput::Error {
                        message: format!(
                            "`size` must be WIDTHxHEIGHT (e.g. 1024x1024), got `{raw}`"
                        ),
                    };
                }
            },
            None => ImageSize::square(1024),
        };
        let mut request = ImageRequest::new(prompt, size);
        if let Some(label) = input.get("label").and_then(|v| v.as_str()) {
            // Otherwise keep the request's own prompt-derived label.
            request.label = label.to_string();
        }

        let artifact = match self.0.generate_image(request).await {
            Ok(a) => a,
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("image generation failed: {e}"),
                };
            }
        };

        let store = match ArtifactStore::open(root.join(".stella").join("artifacts")) {
            Ok(s) => s,
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("artifact store unavailable: {e}"),
                };
            }
        };
        match store.save_artifact(&artifact) {
            Ok(saved) => ToolOutput::Ok {
                content: format!(
                    "generated \"{}\" → {} ({}, model {}, ${:.4})",
                    saved.label, saved.path, size, artifact.model, artifact.cost_usd
                ),
            },
            Err(e) => ToolOutput::Error {
                message: format!("could not persist the artifact: {e}"),
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use stella_media::{
        MediaArtifact, MediaCapabilities, MediaError, MediaJob, MediaJobStatus, MediaKind,
        VideoRequest,
    };

    /// A deterministic in-memory provider: one fixed PNG-ish artifact, no
    /// network — the same fake-backed seam discipline as the fleet/monitor
    /// ports.
    struct FakeImages;

    #[async_trait]
    impl MediaProvider for FakeImages {
        fn id(&self) -> &str {
            "fake"
        }
        fn capabilities(&self) -> MediaCapabilities {
            MediaCapabilities::default()
        }
        async fn generate_image(&self, req: ImageRequest) -> Result<MediaArtifact, MediaError> {
            if req.prompt.contains("refuse me") {
                return Err(MediaError::ContentPolicy("test refusal".into()));
            }
            Ok(MediaArtifact {
                kind: MediaKind::Image,
                bytes: vec![0x89, b'P', b'N', b'G'],
                extension: "png".into(),
                label: req.label,
                model: "fake-image-1".into(),
                cost_usd: 0.01,
            })
        }
        async fn generate_video(&self, _req: VideoRequest) -> Result<MediaJob, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
        async fn poll_video(&self, _job: &MediaJob) -> Result<MediaJobStatus, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
    }

    fn tool() -> GenerateImage {
        GenerateImage(Arc::new(FakeImages))
    }

    #[test]
    fn schema_is_mutating_and_named() {
        let schema = tool().schema();
        assert_eq!(schema.name, "generate_image");
        assert!(!schema.read_only);
    }

    #[tokio::test]
    async fn generates_and_persists_under_stella_artifacts() {
        let dir = tempfile::tempdir().expect("tempdir");
        let out = tool()
            .execute(
                &serde_json::json!({"prompt": "a star", "label": "star"}),
                dir.path(),
            )
            .await;
        match out {
            ToolOutput::Ok { content } => {
                assert!(content.contains("star"), "labels the artifact: {content}");
                assert!(content.contains("fake-image-1"), "names the model");
                // The artifact actually landed inside .stella/artifacts/.
                let artifacts = dir.path().join(".stella").join("artifacts");
                let count = std::fs::read_dir(&artifacts)
                    .map(|d| d.filter_map(Result::ok).count())
                    .unwrap_or(0);
                assert!(count >= 1, "one artifact on disk");
            }
            ToolOutput::Error { message } => panic!("expected success: {message}"),
        }
    }

    #[tokio::test]
    async fn refusal_and_bad_size_and_missing_prompt_are_named_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        let refused = tool()
            .execute(&serde_json::json!({"prompt": "refuse me"}), dir.path())
            .await;
        match refused {
            ToolOutput::Error { message } => assert!(message.contains("content policy")),
            ToolOutput::Ok { .. } => panic!("refusal must surface as an error"),
        }
        let bad_size = tool()
            .execute(
                &serde_json::json!({"prompt": "ok", "size": "huge"}),
                dir.path(),
            )
            .await;
        assert!(matches!(bad_size, ToolOutput::Error { .. }));
        let no_prompt = tool().execute(&serde_json::json!({}), dir.path()).await;
        assert!(matches!(no_prompt, ToolOutput::Error { .. }));
    }
}
